### ISSUE TITLE
1.0.0 checklist

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-stream-dotnet-client#191]
- [x] Address all TODOs in the code
- [x] Synchronize `.editorconfig` with AMQP .NET client ([branch](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/tree/lukebakken/editorconfig))
- [x] Merge https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/190
- [x] Rename `SuperStreamConsumer` to `SuperStreamRawConsumer`
- [x] Review public API and move the `Unshipped` text file to `Shipped`
- [x] Document the new `ILogger`
- [x] Unexpected exceptions should provide information for reporting bugs

**Comment by lukebakken** [comment]
https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/198
